version: '3.2'

services:
  db:
    ports:
      - '${DB_PORT}:3306'
    networks:
      - local
      - public

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    networks:
      - local
      - public
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_ROOT_USERNAME}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    hostname: phpmyadmin
    restart: always

  app:
    ports:
      - "${PORT}:${PORT}"
