version: '3.2'

services:
  db:
    image: mariadb:10.3
    networks:
      - local
      - public
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    hostname: db
    restart: "no"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    networks:
      - local
      - public
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_ROOT_USERNAME}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    hostname: phpmyadmin
    restart: "no"

  app:
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
