version: '3.2'

services:
  db:
    image: mysql:8.0
    networks:
      - local
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    hostname: db
    restart: always

  app:
    depends_on:
      - db
    image: ghcr.io/m-mattia-m/emailing-service-app:latest
    networks:
      - local
      - public
    environment:
      # APP
      PORT: ${PORT}
      # DB
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # ADMIN
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    hostname: app
    restart: always

networks:
  local:
    internal: true
  public:
    internal: false
