name: Docker
on:
  push:
    tags:
      - v*.*.*
    # testing
    branches:
      - feature/docker-ci

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # build
          context: .
          file: .docker/app/Dockerfile
          network: host
          # push
          push: true
          tags: m-mattia-m/emailing-service-app:${GITHUB_REF_NAME}, m-mattia-m/emailing-service-app:latest
